import { desc, eq, lt } from "drizzle-orm";
import { orm } from "./connection.ts";
import { runs } from "./tables.ts";
import { nullableJsonText, setNonNullField } from "./row-values.ts";
export interface RunRecord { dispatchId:string; agentKey:string; adapter?:string; model?:string; workspace?:string; task?:string; state:string; startedAt:number; finishedAt?:number; tokensIn?:number; tokensOut?:number; cacheRead?:number; cacheWrite?:number; cost?:number; turns?:number; result?:unknown; lastError?:string }
type RunRow=typeof runs.$inferSelect;
function rowToRun(row:RunRow):RunRecord { const run:RunRecord={dispatchId:row.dispatchId,agentKey:row.agentKey,state:row.state,startedAt:row.startedAt};setNonNullField(run,"adapter",row.adapter);setNonNullField(run,"model",row.model);setNonNullField(run,"workspace",row.workspace);setNonNullField(run,"task",row.task);setNonNullField(run,"finishedAt",row.finishedAt);setNonNullField(run,"tokensIn",row.tokensIn);setNonNullField(run,"tokensOut",row.tokensOut);setNonNullField(run,"cacheRead",row.cacheRead);setNonNullField(run,"cacheWrite",row.cacheWrite);setNonNullField(run,"cost",row.cost);setNonNullField(run,"turns",row.turns);setNonNullField(run,"result",row.result===null?null:JSON.parse(row.result));setNonNullField(run,"lastError",row.lastError);return run;}
export function upsertRun(d:string,r:RunRecord):void{orm(d).insert(runs).values({dispatchId:r.dispatchId,agentKey:r.agentKey,adapter:r.adapter??null,model:r.model??null,workspace:r.workspace??null,task:r.task??null,state:r.state,startedAt:r.startedAt,finishedAt:r.finishedAt??null,tokensIn:r.tokensIn??null,tokensOut:r.tokensOut??null,cacheRead:r.cacheRead??null,cacheWrite:r.cacheWrite??null,cost:r.cost??null,turns:r.turns??null,result:nullableJsonText(r.result),lastError:r.lastError??null}).onConflictDoUpdate({target:runs.dispatchId,set:{agentKey:r.agentKey,adapter:r.adapter??null,model:r.model??null,workspace:r.workspace??null,task:r.task??null,state:r.state,finishedAt:r.finishedAt??null,tokensIn:r.tokensIn??null,tokensOut:r.tokensOut??null,cacheRead:r.cacheRead??null,cacheWrite:r.cacheWrite??null,cost:r.cost??null,turns:r.turns??null,result:nullableJsonText(r.result),lastError:r.lastError??null}}).run();}
export function selectRuns(d:string,o:{agentKey?:string;limit?:number}={}):RunRecord[]{const where=o.agentKey===undefined?undefined:eq(runs.agentKey,o.agentKey);const query=orm(d).select().from(runs).where(where).orderBy(desc(runs.startedAt));return (o.limit===undefined?query:query.limit(o.limit)).all().map(rowToRun);}
export function deleteRunsBefore(d:string,c:number):number{return Number(orm(d).delete(runs).where(lt(runs.startedAt,c)).run().changes);}
