CREATE TABLE `agent_status` (
	`agent_id` text PRIMARY KEY,
	`state` text NOT NULL,
	`last_error` text,
	`model_provider` text,
	`model_id` text,
	`thinking` text,
	`task` text,
	`dispatch_id` text,
	`last_text` text,
	`current_file` text,
	`files_touched` text,
	`tokens_in` integer,
	`tokens_out` integer,
	`cache_read` integer,
	`cache_write` integer,
	`cost` real,
	`context_tokens` integer,
	`context_percent` real,
	`turns` integer,
	`session_path` text,
	`session_id` text,
	`project` text,
	`extension_hash` text,
	`started_at` integer,
	`finished_at` integer,
	`updated_at` integer NOT NULL,
	`blocked_message` text,
	CONSTRAINT `fk_agent_status_agent_id_agents_id_fk` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE
);
